<literal> ::= <char_lit> |
              <string> |
              <numeric_literal>

<numeric_literal> ::= ("-" | E) (<digit>+ |
                      "0x" <hex_digit>+ |
                      "0X" <hex_digit>+ |
                      <float_literal>)
                      
<float_literal> ::= ("-" | E) <digit>+ "." <digit>* (("e" | "E") ("-" | E) <digit>+ | E) 